### PR TITLE
sphinx theme from conda-forge

### PR DESCRIPTION
**Pull request by brian-rose**
Testing whether we can build with the theme from conda-forge instead of pip

### CODE REVIEW

**Comment by brian-rose** [comment]
Had to remove the obsolete version pins in the cookbook actions, https://github.com/ProjectPythia/cookbook-actions/pull/108

**Comment by brian-rose** [comment]
This is working! We are now installing the sphinx theme from conda-forge.

**Comment by brian-rose** [comment]
The goal of this PR is to simplify the environment file in the Cookbook template as much as possible. We want to let conda / mamba handle all the dependencies.

**Comment by erogluorhan** [comment]
Please hold this for now as there is a dependency mismatch in Conda version that showed up in. the portal tests I ran.

**Comment by erogluorhan** [comment]
This can be closed now as PR #163 handled this and got merged.

**Pull request closed without merging**
