### PR TITLE
http->https for binderhub url

### PR DESCRIPTION
**Pull request by tylere**

### CODE REVIEW

**Comment by tylere** [comment]
This should prevent future occurrences of https://github.com/ProjectPythia/cookbook-gallery/issues/125

**Comment by brian-rose** [comment]
Hi @tylere, thanks for opening this!
My understanding is that our experimental binderhub is only running under http, not https. Is that still the case @ktyle?

**Comment by ktyle** [comment]
Yes, it is only http at this time. Once we provision our new ACCESS-provided instance, we will configure the Binderhub to support https.

**Comment by brian-rose** [comment]
We've now updated the _config file to point to the new Pythia binder which uses https.

**Pull request closed without merging**
