### PR TITLE
Remove prettier from pre-commit

### PR DESCRIPTION
**Pull request by brian-rose**
As suggested by @dopplershift, due to the continued aggravation of pre-commit opening PRs that include pre-release alpha versions of prettier, this PR just removes prettier entirely from our pre-commit config.

### CODE REVIEW

**Comment by brian-rose** [comment]
Other repos that suffer from the same issue include
- [Foundations](https://github.com/ProjectPythia/pythia-foundations/blob/2101e019fb2fd0f9fbf79e6256ac5b2d1daf2600/.pre-commit-config.yaml#L36)
- [pythia-datasets](https://github.com/ProjectPythia/pythia-datasets/blob/971a06edbad62f42a67bfb115af816bf578a3e0b/.pre-commit-config.yaml#L32)
- [.github](https://github.com/ProjectPythia/.github/blob/698c25b57161e4ca9bf73f537e42abd0c2ba722b/.pre-commit-config.yaml#L11)
- Some (but not all) individual cookbook repos

**Comment by brian-rose** [comment]
@dopplershift are you aware of any issue tracking the problem with pre-commit and prettier releases that we can link here?

It would be great to get the functionality of prettier back once the headaches are resolved.

**Comment by dopplershift** [comment]
Let's just say [upstream is less than interested](https://github.com/pre-commit/pre-commit/issues/995) about doing anything about this. "Working as intended" was one phrase I saw. 🙄

**Comment by dopplershift** [comment]
For the record, an attitude like that from upstream (not the first time I've seen it) has me reconsidering future use of pre-commit in my projects.

**Comment by brian-rose** [comment]
Good to know that there's essentially zero chance of an upcoming change in how pre-commit handles these cases.

Are we happy with the compromise of just removing prettier from the pre-commit list, and thus losing its functionality? Here and in several other of our repos?

**Comment by brian-rose** [comment]
There might be a viable alternative: keep using prettier, but exclude it from auto-updates (and thus need to manually update its version in `.pre-commit-config.yaml` when we are ready to upgrade.

If I'm interpreting [these docs](https://pre-commit.ci/#configuration) correctly, we should be able to do this just by adding this block to `.pre-commit-config.yaml`:
```
ci:
    skip: [prettier]
``` 

@dopplershift does that sound correct?

**Comment by dopplershift** [comment]
@brian-rose My read of those docs implies that this will only skip running prettier on the pre-commit CI service, not disable updating the version. I can find no way to dial back updates, only ways to store hashes for versions or use "bleeding edge": https://pre-commit.com/#pre-commit-autoupdate

**Comment by dopplershift** [comment]
@dcamron and I have also found that currently precommit-ci is only set to run on 7 of our own repositories, not any of the cookbook repos (and currently that list would have to be added to manually rather than having "all repositories" set). I think we need to think a little more about what we want the user experience to be, both locally and on GitHub.

**Comment by dcamron** [comment]
Closes #186

**Pull request merged**
