### PR TITLE
pre-commit

### PR DESCRIPTION
**Pull request by norlandrhagen**
- Added .pre-commit config yaml file, which is a copy of the [Pithia Foundations pre-commit config](https://github.com/ProjectPythia/pythia-foundations/blob/main/.pre-commit-config.yaml)
- Ran pre-commit on existing files in the cookbook template

cc @brian-rose

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]

**Comment by norlandrhagen** [comment]
Hey there @brian-rose, thanks for the feedback! 

I'm fine with any of those. Waiting until `prettier 3.0.0` seem fine, definitely don't want to create more tedious cleanup work!

As for exploring option #2, I'm not sure if it works, but can we pin the `prettier` version?
Something like is mentioned in this issue: https://github.com/pre-commit/pre-commit-hooks/issues/332

```python
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies: [prettier@v2.7.1]
```

**Comment by brian-rose** [comment]
> As for exploring option #2, I'm not sure if it works, but can we pin the `prettier` version?

I don't know if it will work either, but let's give it a try! We can try it out here in the template repo for a week or so and see what autoupdates get generated. If we're happy these changes, then we can migrate them to all the existing cookbook repos.

**Review by brian-rose — APPROVED** [review]

**Comment by brian-rose** [comment]
Thanks for your contribution @norlandrhagen !

**Comment by norlandrhagen** [comment]
Thanks @brian-rose! Not sure if it'll work, but fingers crossed.

**Pull request merged**
